import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, BedDouble, Bot, Boxes, ChevronRight, CircleCheck, Clock3, LayoutDashboard, Map, Menu, RefreshCw, ShieldCheck, Users, X } from 'lucide-react';
import { AreaChart, Area, ResponsiveContainer, Tooltip, XAxis, YAxis, BarChart, Bar } from 'recharts';
import { getDashboard, getRedistribution, getFederated, askAI } from './lib/api';
import './styles.css';

function App(){
 const [data,setData]=useState(null), [page,setPage]=useState('overview'), [menu,setMenu]=useState(false), [ai,setAi]=useState(false), [question,setQuestion]=useState('Which medicines need action today?'), [answer,setAnswer]=useState('');
 const [redistribution,setRedistribution]=useState([]), [fed,setFed]=useState(null);
 useEffect(()=>{Promise.all([getDashboard(),getRedistribution(),getFederated()]).then(([d,r,f])=>{setData(d);setRedistribution(r);setFed(f)}).catch(console.error)},[]);
 if(!data) return <div className="loading"><Activity size={30}/> Loading healthcare command center…</div>;
 const pages={overview:'National Overview',inventory:'Medicine Inventory',beds:'Bed Availability',people:'Personnel Attendance',redistribution:'Redistribution',federated:'Federated AI'};
 const nav=[['overview',LayoutDashboard,'Overview'],['inventory',Boxes,'Medicine Inventory'],['beds',BedDouble,'Beds'],['people',Users,'Personnel'],['redistribution',Map,'Redistribution'],['federated',ShieldCheck,'Federated AI']];
 const runAI=async()=>{setAnswer('Thinking…'); const r=await askAI(question); setAnswer(r.answer||r.error)};
 return <div className="app">
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="logo"><Activity/></div><div><b>HealthFlow AI</b><span>Supply Chain Command</span></div></div><div className="nav">{nav.map(([id,Icon,label])=><button className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}} key={id}><Icon size={18}/>{label}</button>)}</div><div className="side-foot"><div className="secure"><CircleCheck size={16}/><span>System operational</span></div><small>Prototype • BRICS-ready architecture</small></div></aside>
  {menu&&<div className="backdrop" onClick={()=>setMenu(false)}/>}<main className="main"><header><button className="mobile-menu" onClick={()=>setMenu(!menu)}><Menu/></button><div><p className="eyebrow">National Healthcare Resource Network</p><h1>{pages[page]}</h1></div><button className="ai-btn" onClick={()=>setAi(true)}><Bot size={18}/> AI Copilot</button></header>
  {page==='overview'&&<Overview data={data} setPage={setPage}/>} {page==='inventory'&&<Inventory data={data}/>} {page==='beds'&&<Beds data={data}/>} {page==='people'&&<People data={data}/>} {page==='redistribution'&&<Redistribution items={redistribution}/>} {page==='federated'&&<Federated fed={fed}/>} 
  </main>
  {ai&&<div className="modal-wrap"><div className="modal"><div className="modal-head"><div><p className="eyebrow">Gemini-powered</p><h2>Healthcare AI Copilot</h2></div><button onClick={()=>setAi(false)}><X/></button></div><p className="muted">Ask about inventory, stock-out risks, bed capacity or redistribution.</p><div className="chips">{['Which medicines need action today?','Where should we redistribute stock?','Summarize emergency capacity.'].map(x=><button onClick={()=>setQuestion(x)} key={x}>{x}</button>)}</div><textarea value={question} onChange={e=>setQuestion(e.target.value)}/><button className="primary" onClick={runAI}><Bot size={17}/> Ask Gemini</button>{answer&&<div className="answer">{answer}</div>}</div></div>}
 </div>
}
function KPI({icon:Icon,label,value,sub,alert}){return <div className="kpi"><div className="kpi-icon"><Icon size={20}/></div><div><span>{label}</span><strong className={alert?'danger':''}>{value}</strong><small>{sub}</small></div></div>}
function Overview({data,setPage}){return <div className="content"><section className="hero"><div><span className="pill"><Activity size={14}/> LIVE MONITORING</span><h2>Healthcare resources,<br/><em>visible before they become critical.</em></h2><p>AI-assisted visibility across medicines, beds and personnel with early warnings and cross-district action.</p></div><div className="hero-stat"><span>Network readiness</span><b>94%</b><div className="progress"><i style={{width:'94%'}}/></div><small>Based on current inventory, capacity & attendance</small></div></section><div className="kpis"><KPI icon={Boxes} label="Medicines tracked" value={data.kpis.medicinesTracked} sub="Across pilot districts"/><KPI icon={AlertTriangle} label="Stock-out alerts" value={data.kpis.stockoutAlerts} sub="Require attention" alert/><KPI icon={BedDouble} label="Beds available" value={data.kpis.bedsAvailable} sub={`${data.kpis.bedOccupancy}% occupancy`}/><KPI icon={Users} label="Personnel attendance" value={`${data.kpis.attendance}%`} sub="Today across PHCs"/></div><div className="grid two"><section className="card"><div className="card-head"><div><h3>Medicine risk monitor</h3><p>AI-assisted 7-day stock-out risk</p></div><button className="text-btn" onClick={()=>setPage('inventory')}>View inventory <ChevronRight size={15}/></button></div><div className="risk-list">{data.medicines.slice(0,5).map(m=><div className="risk-row" key={m.id}><div className="med-dot">{m.name[0]}</div><div className="med-name"><b>{m.name}</b><span>{m.stock.toLocaleString()} {m.unit} remaining</span></div><div className="spark"><ResponsiveContainer width="100%" height={42}><AreaChart data={m.analytics.forecast.map((v,i)=>({i,v}))}><Area type="monotone" dataKey="v" fill="currentColor" stroke="currentColor" fillOpacity={.12}/></AreaChart></ResponsiveContainer></div><div className={`risk ${m.analytics.level.toLowerCase()}`}>{m.analytics.level}<small>{m.analytics.daysOfCover}d cover</small></div></div>)}</div></section><section className="card"><div className="card-head"><div><h3>Facility capacity</h3><p>Current bed utilization</p></div></div><div className="facility-chart"><ResponsiveContainer width="100%" height={250}><BarChart data={data.facilities.map(f=>({name:f.name.replace(' PHC',''),occupied:f.occupied,available:f.beds-f.occupied}))}><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Bar dataKey="occupied" stackId="a" fill="currentColor"/><Bar dataKey="available" stackId="a" fill="currentColor" fillOpacity={.18}/></BarChart></ResponsiveContainer></div></section></div><section className="alert-strip"><AlertTriangle/><div><b>{data.alerts.length} medicine risk signals detected</b><span>Open the inventory view to review projected demand and days of cover.</span></div><button onClick={()=>setPage('inventory')}>Review alerts <ChevronRight/></button></section></div>}
function Inventory({data}){return <div className="content"><div className="section-intro"><div><p className="eyebrow">Real-time inventory</p><h2>Medicine stock intelligence</h2><p>Risk scores combine current stock, reorder thresholds and recent demand trends.</p></div><button className="refresh"><RefreshCw size={16}/> Refresh</button></div><div className="table-card"><table><thead><tr><th>Medicine</th><th>District</th><th>Stock</th><th>Daily demand</th><th>Days cover</th><th>7-day forecast</th><th>Risk</th></tr></thead><tbody>{data.medicines.map(m=><tr key={m.id}><td><b>{m.name}</b><span>{m.category}</span></td><td>{data.districts.find(d=>d.id===m.districtId)?.name}</td><td>{m.stock.toLocaleString()} {m.unit}</td><td>{m.dailyDemand.toLocaleString()}</td><td>{m.analytics.daysOfCover} days</td><td><div className="mini-chart"><ResponsiveContainer width="100%" height={45}><AreaChart data={m.analytics.forecast.map((v,i)=>({i,v}))}><Area dataKey="v" type="monotone" fill="currentColor" stroke="currentColor" fillOpacity={.1}/></AreaChart></ResponsiveContainer></div></td><td><span className={`risk ${m.analytics.level.toLowerCase()}`}>{m.analytics.level}</span></td></tr>)}</tbody></table></div></div>}
function Beds({data}){return <div className="content"><div className="cards-grid">{data.facilities.map(f=><div className="card facility" key={f.id}><div className="facility-top"><div className="facility-icon"><BedDouble/></div><span className="status-dot">Live</span></div><h3>{f.name}</h3><p>{data.districts.find(d=>d.id===f.districtId)?.name}</p><div className="bed-num"><b>{f.beds-f.occupied}</b><span>available</span></div><div className="progress"><i style={{width:`${f.occupied/f.beds*100}%`}}/></div><div className="split"><span>Occupied <b>{f.occupied}</b></span><span>Total <b>{f.beds}</b></span></div></div>)}</div></div>}
function People({data}){return <div className="content"><div className="table-card"><table><thead><tr><th>Personnel</th><th>Role</th><th>Facility</th><th>Status</th><th>Check-in</th></tr></thead><tbody>{data.personnel.map(p=><tr key={p.id}><td><b>{p.name}</b><span>{p.id}</span></td><td>{p.role}</td><td>{p.facilityId}</td><td><span className={`person-status ${p.status.toLowerCase()}`}>{p.status}</span></td><td>{p.checkIn||'—'}</td></tr>)}</tbody></table></div></div>}
function Redistribution({items}){return <div className="content"><div className="section-intro"><div><p className="eyebrow">AI decision support</p><h2>Cross-district redistribution</h2><p>Recommendations prioritize shortage risk, demand growth and available donor stock.</p></div></div><div className="recommendations">{items.map((x,i)=><div className="recommendation" key={i}><div className="rec-icon"><Map/></div><div className="route"><span>{x.from}</span><ChevronRight/><span>{x.to}</span></div><h3>{x.medicine}</h3><p>{x.reason}</p><div className="rec-foot"><b>Transfer {x.quantity.toLocaleString()} units</b><span className={`risk ${x.priority.toLowerCase()}`}>{x.priority} priority</span></div></div>)}</div></div>}
function Federated({fed}){return <div className="content"><section className="hero federated"><div><span className="pill"><ShieldCheck size={14}/> PRIVACY-AWARE MODEL SHARING</span><h2>Learn nationally,<br/><em>without centralizing raw district data.</em></h2><p>This prototype simulates federated training where districts share aggregate model statistics rather than raw operational records.</p></div><div className="round"><b>{fed?.rounds||0}</b><span>training rounds</span></div></section>{fed&&<><div className="kpis"><KPI icon={Map} label="Participating districts" value={fed.participatingDistricts} sub="Local training nodes"/><KPI icon={Activity} label="Aggregated MAE" value={fed.aggregatedMae} sub="Weighted prototype metric"/><KPI icon={ShieldCheck} label="Raw records shared" value="0" sub="Federated design"/></div><div className="table-card"><table><thead><tr><th>District</th><th>Samples</th><th>Local MAE</th><th>Model</th></tr></thead><tbody>{fed.districtUpdates.map(x=><tr key={x.district}><td><b>{x.district}</b></td><td>{x.samples.toLocaleString()}</td><td>{x.localMae}</td><td>{x.modelVersion}</td></tr>)}</tbody></table></div></>}</div>}

createRoot(document.getElementById('root')).render(<App/>);
